# Generated by Django 2.2.4 on 2019-08-26 06:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('isExplicit', models.BooleanField(default=False)),
                ('musicGenre', models.IntegerField(choices=[(1, 'hipop'), (2, 'afro'), (3, 'indie'), (4, 'k-pop'), (5, 'pop')], default='1', max_length=1)),
                ('image', models.ImageField(default='media/defaults/no-img.jpg', upload_to='media/')),
                ('lyrics', models.TextField()),
                ('musicFile', models.FileField(default='media/defaults/Krazy-Rymz-My-Matter_1lzbZGR.mp3', upload_to='media/')),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
