# Generated by Django 2.2.4 on 2019-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(default='media/images/no-img.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='musicFile',
            field=models.FileField(default='media/audio/def.mp3', upload_to='audio/'),
        ),
    ]
